version: '3.1'

services:
  app:
    container_name: springboot-postgresql
    image: springboot-postgresql
    build: ./
#    expose:
#      - 8080
      #    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
       #    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=root
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: 'postgres:13.1-alpine'
#    container_name: sample_db
#    volumes:
#      - sample_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
#      - PGDATA=/var/lib/postgresql/data/pgdata

